package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Awardrecord;

public interface AwardrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int insert(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int insertSelective(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    Awardrecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int updateByPrimaryKeySelective(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int updateByPrimaryKey(Awardrecord record);
}