package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Awardrecord;

import java.util.List;
import java.util.Map;

public interface AwardrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int insert(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int insertSelective(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    Awardrecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int updateByPrimaryKeySelective(Awardrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AWARDRECORD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    int updateByPrimaryKey(Awardrecord record);

    /**
     * 根据小戏骨成员ID查询小戏骨获奖记录
     *
     * @param paramMap
     * @return
     */
    List<Awardrecord> selectAwardrecordsBySid(Map<String, Object> paramMap);

    /**
     * 根据小戏骨成员ID查询小戏骨获奖记录数量
     *
     * @param paramMap
     * @return
     */
    Long selectAwardrecordsTotalBySid(Map<String, Object> paramMap);
}