package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Episode;

public interface EpisodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    Episode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPISODE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(Episode record);
}