package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Photo;

import java.util.List;
import java.util.Map;

public interface PhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    Photo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(Photo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PHOTO
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(Photo record);

    /**
     * 分页查询小戏骨图片
     *
     * @param paramMap
     * @return
     */
    List<Photo> selectPhotosByPage(Map<String, Object> paramMap);
}