package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starPhotoRelation;

public interface starPhotoRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starPhotoRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starPhotoRelation record);
}