package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.StarPhotoRelation;

public interface StarPhotoRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(StarPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(StarPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    StarPhotoRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(StarPhotoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_PHOTO_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(StarPhotoRelation record);
}