package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starAwardrecordRelation;

public interface starAwardrecordRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starAwardrecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starAwardrecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starAwardrecordRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starAwardrecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starAwardrecordRelation record);
}