package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.StarWorkRelation;

public interface StarWorkRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(StarWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(StarWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    StarWorkRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(StarWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(StarWorkRelation record);
}