package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starActivityRelation;

public interface starActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starActivityRelation record);
}