package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.StarAwardRecordRelation;

public interface StarAwardRecordRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(StarAwardRecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(StarAwardRecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    StarAwardRecordRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(StarAwardRecordRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_AWARDRECORD_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(StarAwardRecordRelation record);
}