package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Star;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    int insert(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    int insertSelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    Star selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    int updateByPrimaryKeySelective(Star record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR
     *
     * @mbggenerated Thu Dec 27 12:40:41 CST 2018
     */
    int updateByPrimaryKey(Star record);
}