package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.StarActivityRelation;

public interface StarActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(StarActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(StarActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    StarActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(StarActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_ACTIVITY_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(StarActivityRelation record);
}