package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starWorkRelation;

public interface starWorkRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starWorkRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starWorkRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_WORK_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starWorkRelation record);
}