package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starVideoRelation;

public interface starVideoRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starVideoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starVideoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starVideoRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starVideoRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_VIDEO_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starVideoRelation record);
}