package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.StarEvaluationRelation;

public interface StarEvaluationRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(StarEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(StarEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    StarEvaluationRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(StarEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(StarEvaluationRelation record);
}