package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.starEvaluationRelation;

public interface starEvaluationRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(starEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(starEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    starEvaluationRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(starEvaluationRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STAR_EVALUATION_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(starEvaluationRelation record);
}