package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.Video;

import java.util.List;
import java.util.Map;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    Video selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VIDEO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(Video record);

    /**
     * 分页查询小戏骨视频
     *
     * @param paramMap
     * @return
     */
    List<Video> selectVideosByPage(Map<String, Object> paramMap);
}