package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.WorkEpisodeRelation;

public interface WorkEpisodeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insert(WorkEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int insertSelective(WorkEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    WorkEpisodeRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKeySelective(WorkEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    int updateByPrimaryKey(WorkEpisodeRelation record);
}