package com.lianggege.xiaoxiguclub.mapper;

import com.lianggege.xiaoxiguclub.model.workEpisodeRelation;

public interface workEpisodeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insert(workEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int insertSelective(workEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    workEpisodeRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKeySelective(workEpisodeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORK_EPISODE_RELATION
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    int updateByPrimaryKey(workEpisodeRelation record);
}