package com.lianggege.xiaoxiguclub.model;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY.INTRO
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY.ACTIVITY_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private Date activityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY.ID
     *
     * @return the value of ACTIVITY.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY.ID
     *
     * @param id the value for ACTIVITY.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY.TITLE
     *
     * @return the value of ACTIVITY.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY.TITLE
     *
     * @param title the value for ACTIVITY.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY.INTRO
     *
     * @return the value of ACTIVITY.INTRO
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY.INTRO
     *
     * @param intro the value for ACTIVITY.INTRO
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY.ACTIVITY_DATE
     *
     * @return the value of ACTIVITY.ACTIVITY_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public Date getActivityDate() {
        return activityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY.ACTIVITY_DATE
     *
     * @param activityDate the value for ACTIVITY.ACTIVITY_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setActivityDate(Date activityDate) {
        this.activityDate = activityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY.SRC
     *
     * @return the value of ACTIVITY.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY.SRC
     *
     * @param src the value for ACTIVITY.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}