package com.lianggege.xiaoxiguclub.model;

import java.util.Date;

public class Awardrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWARDRECORD.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWARDRECORD.ACTIVITY
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWARDRECORD.AWARD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String award;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWARDRECORD.AWARD_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private Date awardDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AWARDRECORD.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWARDRECORD.ID
     *
     * @return the value of AWARDRECORD.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWARDRECORD.ID
     *
     * @param id the value for AWARDRECORD.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWARDRECORD.ACTIVITY
     *
     * @return the value of AWARDRECORD.ACTIVITY
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWARDRECORD.ACTIVITY
     *
     * @param activity the value for AWARDRECORD.ACTIVITY
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWARDRECORD.AWARD
     *
     * @return the value of AWARDRECORD.AWARD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getAward() {
        return award;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWARDRECORD.AWARD
     *
     * @param award the value for AWARDRECORD.AWARD
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setAward(String award) {
        this.award = award == null ? null : award.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWARDRECORD.AWARD_DATE
     *
     * @return the value of AWARDRECORD.AWARD_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public Date getAwardDate() {
        return awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWARDRECORD.AWARD_DATE
     *
     * @param awardDate the value for AWARDRECORD.AWARD_DATE
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setAwardDate(Date awardDate) {
        this.awardDate = awardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AWARDRECORD.SRC
     *
     * @return the value of AWARDRECORD.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AWARDRECORD.SRC
     *
     * @param src the value for AWARDRECORD.SRC
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}