package com.lianggege.xiaoxiguclub.model;

public class Episode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private Short episodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private String vid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.ID
     *
     * @return the value of EPISODE.ID
     *
     * @mbggenerated Thu Dec 27 08:45:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.ID
     *
     * @param id the value for EPISODE.ID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.EPISODE_NUMBER
     *
     * @return the value of EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public Short getEpisodeNumber() {
        return episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.EPISODE_NUMBER
     *
     * @param episodeNumber the value for EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setEpisodeNumber(Short episodeNumber) {
        this.episodeNumber = episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.TITLE
     *
     * @return the value of EPISODE.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.TITLE
     *
     * @param title the value for EPISODE.TITLE
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.VID
     *
     * @return the value of EPISODE.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.VID
     *
     * @param vid the value for EPISODE.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }
}