package com.lianggege.xiaoxiguclub.model;

public class Episode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private Short episodeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPISODE.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.ID
     *
     * @return the value of EPISODE.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.ID
     *
     * @param id the value for EPISODE.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.EPISODE_NUMBER
     *
     * @return the value of EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public Short getEpisodeNumber() {
        return episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.EPISODE_NUMBER
     *
     * @param episodeNumber the value for EPISODE.EPISODE_NUMBER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setEpisodeNumber(Short episodeNumber) {
        this.episodeNumber = episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.TITLE
     *
     * @return the value of EPISODE.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.TITLE
     *
     * @param title the value for EPISODE.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPISODE.SRC
     *
     * @return the value of EPISODE.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPISODE.SRC
     *
     * @param src the value for EPISODE.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}