package com.lianggege.xiaoxiguclub.model;

public class starVideoRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_VIDEO_RELATION.ID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_VIDEO_RELATION.SID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_VIDEO_RELATION.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    private String vid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_VIDEO_RELATION.ID
     *
     * @return the value of STAR_VIDEO_RELATION.ID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_VIDEO_RELATION.ID
     *
     * @param id the value for STAR_VIDEO_RELATION.ID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_VIDEO_RELATION.SID
     *
     * @return the value of STAR_VIDEO_RELATION.SID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_VIDEO_RELATION.SID
     *
     * @param sid the value for STAR_VIDEO_RELATION.SID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_VIDEO_RELATION.VID
     *
     * @return the value of STAR_VIDEO_RELATION.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_VIDEO_RELATION.VID
     *
     * @param vid the value for STAR_VIDEO_RELATION.VID
     *
     * @mbggenerated Thu Dec 27 08:45:15 CST 2018
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }
}