package com.lianggege.xiaoxiguclub.model;

public class StarEvaluationRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_EVALUATION_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_EVALUATION_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_EVALUATION_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_EVALUATION_RELATION.ID
     *
     * @return the value of STAR_EVALUATION_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_EVALUATION_RELATION.ID
     *
     * @param id the value for STAR_EVALUATION_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_EVALUATION_RELATION.SID
     *
     * @return the value of STAR_EVALUATION_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_EVALUATION_RELATION.SID
     *
     * @param sid the value for STAR_EVALUATION_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_EVALUATION_RELATION.EID
     *
     * @return the value of STAR_EVALUATION_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_EVALUATION_RELATION.EID
     *
     * @param eid the value for STAR_EVALUATION_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }
}