package com.lianggege.xiaoxiguclub.model;

public class StarWorkRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_WORK_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_WORK_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_WORK_RELATION.ROLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_WORK_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String wid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_WORK_RELATION.ID
     *
     * @return the value of STAR_WORK_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_WORK_RELATION.ID
     *
     * @param id the value for STAR_WORK_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_WORK_RELATION.SID
     *
     * @return the value of STAR_WORK_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_WORK_RELATION.SID
     *
     * @param sid the value for STAR_WORK_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_WORK_RELATION.ROLE
     *
     * @return the value of STAR_WORK_RELATION.ROLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_WORK_RELATION.ROLE
     *
     * @param role the value for STAR_WORK_RELATION.ROLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_WORK_RELATION.WID
     *
     * @return the value of STAR_WORK_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_WORK_RELATION.WID
     *
     * @param wid the value for STAR_WORK_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setWid(String wid) {
        this.wid = wid == null ? null : wid.trim();
    }
}