package com.lianggege.xiaoxiguclub.model;

public class StarPhotoRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_PHOTO_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_PHOTO_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_PHOTO_RELATION.PID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_PHOTO_RELATION.ID
     *
     * @return the value of STAR_PHOTO_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_PHOTO_RELATION.ID
     *
     * @param id the value for STAR_PHOTO_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_PHOTO_RELATION.SID
     *
     * @return the value of STAR_PHOTO_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_PHOTO_RELATION.SID
     *
     * @param sid the value for STAR_PHOTO_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_PHOTO_RELATION.PID
     *
     * @return the value of STAR_PHOTO_RELATION.PID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_PHOTO_RELATION.PID
     *
     * @param pid the value for STAR_PHOTO_RELATION.PID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }
}