package com.lianggege.xiaoxiguclub.model;

import java.util.Date;

public class Star {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.NAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.ALIAS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.SEX
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.HOMETOWN
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String hometown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.CONSTELLATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String constellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.COMPANY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.AVATAR
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.WB_NICKNAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String wbNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.WB_HOMEPAGE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String wbHomepage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String defaultdisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.ID
     *
     * @return the value of STAR.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.ID
     *
     * @param id the value for STAR.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.NAME
     *
     * @return the value of STAR.NAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.NAME
     *
     * @param name the value for STAR.NAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.ALIAS
     *
     * @return the value of STAR.ALIAS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.ALIAS
     *
     * @param alias the value for STAR.ALIAS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias == null ? null : alias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.SEX
     *
     * @return the value of STAR.SEX
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.SEX
     *
     * @param sex the value for STAR.SEX
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.BIRTHDAY
     *
     * @return the value of STAR.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.BIRTHDAY
     *
     * @param birthday the value for STAR.BIRTHDAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.HOMETOWN
     *
     * @return the value of STAR.HOMETOWN
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getHometown() {
        return hometown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.HOMETOWN
     *
     * @param hometown the value for STAR.HOMETOWN
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setHometown(String hometown) {
        this.hometown = hometown == null ? null : hometown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.CONSTELLATION
     *
     * @return the value of STAR.CONSTELLATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getConstellation() {
        return constellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.CONSTELLATION
     *
     * @param constellation the value for STAR.CONSTELLATION
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setConstellation(String constellation) {
        this.constellation = constellation == null ? null : constellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.COMPANY
     *
     * @return the value of STAR.COMPANY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.COMPANY
     *
     * @param company the value for STAR.COMPANY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.AVATAR
     *
     * @return the value of STAR.AVATAR
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.AVATAR
     *
     * @param avatar the value for STAR.AVATAR
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.WB_NICKNAME
     *
     * @return the value of STAR.WB_NICKNAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getWbNickname() {
        return wbNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.WB_NICKNAME
     *
     * @param wbNickname the value for STAR.WB_NICKNAME
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setWbNickname(String wbNickname) {
        this.wbNickname = wbNickname == null ? null : wbNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.WB_HOMEPAGE
     *
     * @return the value of STAR.WB_HOMEPAGE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getWbHomepage() {
        return wbHomepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.WB_HOMEPAGE
     *
     * @param wbHomepage the value for STAR.WB_HOMEPAGE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setWbHomepage(String wbHomepage) {
        this.wbHomepage = wbHomepage == null ? null : wbHomepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR.DEFAULTDISPLAY
     *
     * @return the value of STAR.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getDefaultdisplay() {
        return defaultdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR.DEFAULTDISPLAY
     *
     * @param defaultdisplay the value for STAR.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setDefaultdisplay(String defaultdisplay) {
        this.defaultdisplay = defaultdisplay == null ? null : defaultdisplay.trim();
    }
}