package com.lianggege.xiaoxiguclub.model;

public class StarAwardRecordRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_AWARDRECORD_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_AWARDRECORD_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_AWARDRECORD_RELATION.RID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_AWARDRECORD_RELATION.ID
     *
     * @return the value of STAR_AWARDRECORD_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_AWARDRECORD_RELATION.ID
     *
     * @param id the value for STAR_AWARDRECORD_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_AWARDRECORD_RELATION.SID
     *
     * @return the value of STAR_AWARDRECORD_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_AWARDRECORD_RELATION.SID
     *
     * @param sid the value for STAR_AWARDRECORD_RELATION.SID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_AWARDRECORD_RELATION.RID
     *
     * @return the value of STAR_AWARDRECORD_RELATION.RID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_AWARDRECORD_RELATION.RID
     *
     * @param rid the value for STAR_AWARDRECORD_RELATION.RID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }
}