package com.lianggege.xiaoxiguclub.model;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.ID
     *
     * @return the value of VIDEO.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.ID
     *
     * @param id the value for VIDEO.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.TITLE
     *
     * @return the value of VIDEO.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.TITLE
     *
     * @param title the value for VIDEO.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.RELEASE_DATE
     *
     * @return the value of VIDEO.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.RELEASE_DATE
     *
     * @param releaseDate the value for VIDEO.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.SRC
     *
     * @return the value of VIDEO.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.SRC
     *
     * @param src the value for VIDEO.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}