package com.lianggege.xiaoxiguclub.model;

public class WorkEpisodeRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EPISODE_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EPISODE_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK_EPISODE_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EPISODE_RELATION.ID
     *
     * @return the value of WORK_EPISODE_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EPISODE_RELATION.ID
     *
     * @param id the value for WORK_EPISODE_RELATION.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EPISODE_RELATION.WID
     *
     * @return the value of WORK_EPISODE_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EPISODE_RELATION.WID
     *
     * @param wid the value for WORK_EPISODE_RELATION.WID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setWid(String wid) {
        this.wid = wid == null ? null : wid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK_EPISODE_RELATION.EID
     *
     * @return the value of WORK_EPISODE_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK_EPISODE_RELATION.EID
     *
     * @param eid the value for WORK_EPISODE_RELATION.EID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }
}