package com.lianggege.xiaoxiguclub.model;

import java.util.Date;

public class Work {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.INTRO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.COVER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String cover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.STATUS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String src;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.ISXXGWORK
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String isxxgwork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORK.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    private String defaultdisplay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.ID
     *
     * @return the value of WORK.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.ID
     *
     * @param id the value for WORK.ID
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.TITLE
     *
     * @return the value of WORK.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.TITLE
     *
     * @param title the value for WORK.TITLE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.INTRO
     *
     * @return the value of WORK.INTRO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.INTRO
     *
     * @param intro the value for WORK.INTRO
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.COVER
     *
     * @return the value of WORK.COVER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.COVER
     *
     * @param cover the value for WORK.COVER
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.RELEASE_DATE
     *
     * @return the value of WORK.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.RELEASE_DATE
     *
     * @param releaseDate the value for WORK.RELEASE_DATE
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.STATUS
     *
     * @return the value of WORK.STATUS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.STATUS
     *
     * @param status the value for WORK.STATUS
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.SRC
     *
     * @return the value of WORK.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.SRC
     *
     * @param src the value for WORK.SRC
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.ISXXGWORK
     *
     * @return the value of WORK.ISXXGWORK
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getIsxxgwork() {
        return isxxgwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.ISXXGWORK
     *
     * @param isxxgwork the value for WORK.ISXXGWORK
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setIsxxgwork(String isxxgwork) {
        this.isxxgwork = isxxgwork == null ? null : isxxgwork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORK.DEFAULTDISPLAY
     *
     * @return the value of WORK.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public String getDefaultdisplay() {
        return defaultdisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORK.DEFAULTDISPLAY
     *
     * @param defaultdisplay the value for WORK.DEFAULTDISPLAY
     *
     * @mbggenerated Mon Dec 31 17:19:31 CST 2018
     */
    public void setDefaultdisplay(String defaultdisplay) {
        this.defaultdisplay = defaultdisplay == null ? null : defaultdisplay.trim();
    }
}